pipeline:
  name: test-pandas
  identifier: testpandas
  projectIdentifier: DhrubaCI
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: dhrubaaccountconnector
        repoName: pandas
        build: <+input>
  stages:
    - stage:
        name: bit linux
        identifier: Bit_linux
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - step:
                  type: Run
                  name: docker builds
                  identifier: docker_builds
                  spec:
                    shell: Sh
                    command: |-
                      docker pull quay.io/pypa/manylinux2014_i686
                      docker run --platform linux/386 -v $(pwd):/pandas quay.io/pypa/manylinux2014_i686 \
                      /bin/bash -xc "cd pandas && \
                      git config --global --add safe.directory /pandas && \
                      /opt/python/cp38-cp38/bin/python -m venv ~/virtualenvs/pandas-dev && \
                      . ~/virtualenvs/pandas-dev/bin/activate && \
                      python -m pip install --no-deps -U pip wheel 'setuptools<60.0.0' && \
                      python -m pip install versioneer[toml] && \
                      python -m pip install cython numpy python-dateutil pytz pytest pytest-xdist pytest-asyncio>=0.17 hypothesis && \
                      python setup.py build_ext -q -j1 && \
                      python -m pip install --no-build-isolation --no-use-pep517 -e . && \
                      python -m pip list && \
                      export PANDAS_CI=1 && \
                      pytest -m 'not slow and not network and not clipboard and not single_cpu' pandas --junitxml=test-data.xml"
    - stage:
        name: asv bot
        identifier: asv_bot
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - step:
                  type: Plugin
                  name: Set up Conda
                  identifier: Checkout
                  spec:
                    connectorRef: account.harnessImage
                    image: continuumio/anaconda3
                    settings:
                      uses: ./.github/actions/setup-conda
    - stage:
        name: code-checks
        identifier: codechecks
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - parallel:
                  - step:
                      type: Plugin
                      name: Install Python
                      identifier: Install_Python
                      spec:
                        connectorRef: DhrubajyotiDocker
                        image: plugins/github-actions
                        settings:
                          uses: actions/setup-python@v4
                          with:
                            python-version: "3.9"
                  - step:
                      type: Plugin
                      name: Run pre-commit
                      identifier: Run_precommit
                      spec:
                        connectorRef: DhrubajyotiDocker
                        image: plugins/download
                        settings:
                          uses: pre-commit/action@v2.0.3
                          with:
                            extra_args: "--verbose --all-files"
                  - step:
                      type: Plugin
                      name: Set up Conda
                      identifier: Set_up_Conda
                      spec:
                        connectorRef: DhrubajyotiDocker
                        image: plugins/github-actions
                        settings:
                          uses: ./.github/actions/setup-conda
                  - step:
                      type: Plugin
                      name: Build Pandas
                      identifier: Build_Pandas
                      spec:
                        connectorRef: DhrubajyotiDocker
                        image: plugins/github-actions
                        settings:
                          uses: ./.github/actions/build_pandas
              - step:
                  type: Run
                  name: Run checks
                  identifier: Run_checks
                  spec:
                    shell: Sh
                    command: ci/code_checks.sh <+matrix.deps>
                  when:
                    stageStatus: Success
                    condition: <+pipeline.stages.cond.spec.execution.steps.echo.status> == "SUCCEEDED"
                  failureStrategies: []
                  strategy:
                    matrix:
                      deps:
                        - single-docs
                        - code
                        - doctests
                        - docstrings
                        - notebooks
                      maxConcurrency: 1
        variables:
          - name: ENV_FILE
            type: String
            description: ""
            value: environment.yml
          - name: PANDAS_CI
            type: Number
            description: ""
            value: 1
  allowStageExecutions: true
